python3 rrtmg_lw.py aggregate ssp_db.Aggregate.gamma.0p100
python3 rrtmg_lw.py bulletrosette ssp_db.BulletRosette.gamma.0p100
python3 rrtmg_lw.py droxtals ssp_db.Droxtal.gamma.0p100
python3 rrtmg_lw.py droxtals2 ssp_db.Droxtal.gamma.0p100
python3 rrtmg_lw.py hollowcol ssp_db.HollowCol.gamma.0p100
python3 rrtmg_lw.py plates ssp_db.Plate.gamma.0p100
python3 rrtmg_lw.py solidcol ssp_db.SolidCol.gamma.0p100
python3 rrtmg_lw.py spheres ssp_db.mie_ice.gamma_sigma_0p100
python3 rrtmg_lw.py spheroids ssp_db.Spheroid.gamma.0p100
